FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

RUN apt-get update -y
RUN apt-get install -y cmake extra-cmake-modules libqt5webkit5-dev libqt5x11extras5-dev libarchive-dev libsqlite3-dev libxcb-keysyms1-dev qtwebengine5-dev curl
